[30기 박영서] Create: 필터링 기능 구현
wecode-bootcamp-korea/30-1st-chadamhwa-backend pull request #2
Opened 2022-03-03 07:51 UTC by YEONG-CTRL

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 최신업데이트 순, 가격 , 리뷰 평점, 카페인 여부 를 통해 상품을 정렬하고자 합니다

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. 업데이트 정렬
- Drink의 데이터 값들을 updated_at을 통해 최신순(내림차순)으로 정렬

2. 가격 정렬
- 가격의 범위에 맞는 값들을 불러온 뒤, 이를 가격에 따라 정렬(오름차순)

3. 리뷰 정렬
- 상품에 해당하는 리뷰들의 rating 평균을 낸 뒤, 이를 기준으로 상품을 정렬 

4. 카페인 정렬
- 카페인이 있는 경우와 없는 경우를 분리하여, 이에 따라 정렬. 카페인이 있는 경우 카페인이 적은 순으로 정렬

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- 상품 정렬에 있어서, 구분 기준이 모호한 경우(카페인이 있냐, 없냐로 나눴을때, 있는 경우 상품들은 어떻게 정렬할지 등) 어떻게 추가적으로 정렬할지 고민할 수 있었습니다
- 딕셔너리를 값에 따라 정렬한 뒤 이를 통해 정렬된 값을 꺼낼 수 있었습니다 

<br />

## :: 기타 질문 및 특이 사항

2022-03-04 02:06 UTC, kyeongraekim requested changes
Filtering 과 관련된 데이터를 기능에 충실하게 잘 만들어주셨네요. 다만 작성해 주신 내용은 곰곰히 생각해보면  서비스 코드 기능면에서 불필요한 View 인 것 같습니다.

모든 상품은 Product view에서 뽑아 올 수 있을 것이고 아래 해당 필터링은 Query Parameter의 형태로 GET 메소드로 함께 들어온 내용을 토대로 Product View에서 동시에 적용할 수 있을 겁니다.

제가 설명드린 내용 곰곰히 생각해보시고 혹시 이해가 안되시거나 궁금한 내용 있으시면 언제든 질문 주세요!

2022-03-06 12:35 UTC, kyeongraekim requested changes
아래 내용 참고하여 수정해주세요!~

2022-03-06 12:35 UTC, kyeongraekim commented on drinks/views.py
> +class ProductsView(View):
제가 의도해드린대로 잘 반영해주셨네요!

2022-03-06 12:35 UTC, kyeongraekim commented on drinks/views.py
> +            categories = category.split(',')
해당 부분에서 split 함수의 의도가 어떻게 될까요? 복수의 내용이 리스트로 담긴다면 파이썬 딕셔너리 get() 메소드 말고 getlist() 도 있음을 확인해주세요!

2022-03-06 12:35 UTC, kyeongraekim commented on drinks/views.py
> +                q.add(Q(caffeine__exact=0), Q.AND)
caffeine 에 해당되는 부분은 문자열 yes/no 가 아닌 Boolean True/False로 수정해주세요!

2022-03-06 12:35 UTC, kyeongraekim commented on drinks/views.py
> +        recently = request.GET.get("recently", None)
recently 보다는 newest, oldest 등의 직관적인 영어 단어를 사용해주세요~

2022-03-06 12:35 UTC, kyeongraekim commented on drinks/views.py
> +            for i in sorted_dict:
'i' 와 같은 모호한 변수명은 웹개발 코딩에서는 사용을 지양해주세요

2022-03-06 12:35 UTC, kyeongraekim commented on drinks/views.py
> +        if caffeine:
불필요한 if-elif로의 분기로 보여지네요.

2022-03-06 12:35 UTC, kyeongraekim commented on drinks/views.py
> +        return JsonResponse({'message':whole_data_list}, status = 200)
- 로직과 관련해서 기능에 충만하게 잘 작성해주셨지만 전체 내용과 관련, 불필요한 함수문들이 너무 많이 작성되어 있습니다. 함수는 처음 선언한 get으로 충분하며 해당 함수 안에서 위와 같이 여러개의 함수를 선언하는 것은 불필요 합니다. 원하신다면 따로 모듈화 과정을 통해 밖으로 빼는 모습이 더 보기 좋을 것 같지만, 그 전에 전체 데이터를 하나의 거대한 json 데이터로 보내는데 있어서 부가적인 함수 선언이 불필요하게 적용 되어있음을 다시 한 번 강조해드립니다.
- 그리고 정렬 기능을 위해서 위와 같이 작성해주신 것 같은데 위 내용은 장고 queryset 문인 order_by() 메소드를 사용하시면 보다 쉽게 해결 될 것 같아 보이네요!
- 그리고 리팩토링 시 리스트를 생성하실 때 append문 말고 리스트 컴프리헨션을 한 번 활용해주세요!

2022-03-06 23:52 UTC, YEONG-CTRL commented on drinks/views.py
> +            categories = category.split(',')
여러개의 차 종류를 쿼리 파라미터로 받고, 이것으로 categories라는 리스트를 생성하여,  해당 리스트에 __in의 field lookup을 쓰려는 것이 의도였습니다. 
getlist를 사용할 시, `?category=과일차,녹차`  의 입력을 받았을 때, `['과일차,녹차'] ` 이렇게 안에 쉼표가 들어간 하나의 값을 가진 리스트가 생성됐습니다. 
반면에 get으로 똑같은 입력을 받은 이후, 이를 split 함수를 이용하여 나눠준 경우, 의도한 대로 ['과일차', '녹차'] 이런식으로 값이 분리된 리스트가 생성됨을 확인했습니다.  
getlist로 요청을 받고, 이를 `categories = category[0].split(',')` 이러한 방식으로 나눠줄 수도 있는데, 어떤 것이 더 좋은 방식인지는 잘 모르겠습니다. 일단 해당 방식으로 수정해서 다시 push했습니다

2022-03-06 23:54 UTC, YEONG-CTRL commented on drinks/views.py
> +        if caffeine:
수정했습니다!

2022-03-06 23:54 UTC, YEONG-CTRL commented on drinks/views.py
> +            for i in sorted_dict:
수정했습니다!

2022-03-06 23:54 UTC, YEONG-CTRL commented on drinks/views.py
> +        recently = request.GET.get("recently", None)
수정했습니다!

2022-03-06 23:54 UTC, YEONG-CTRL commented on drinks/views.py
> +                q.add(Q(caffeine__exact=0), Q.AND)
수정했습니다!

2022-03-07 02:30 UTC, YEONG-CTRL commented on drinks/views.py
> +        return JsonResponse({'message':whole_data_list}, status = 200)
compute_reviews 함수와 , make_whole_data_list함수는  필터링한 쿼리셋을 정렬하는 과정에서 리뷰의 총 갯수와, 리뷰에 달린 평점(rating)의 평균을 구하기 위해 작성했습니다.
함수로 모듈화하지 않으면, if newest - elif rating - else 로 분기되는 정렬 과정에서 똑같은 코드가 계속 반복되야 하는데, 이는 가독성을 낮추는 좋지 않은 코드 진행이라 생각하여 함수로 따로 처리했습니다.
현재는 일단 utils.py 를 작성하여 모듈화 한 이후 import해서 사용하는 것으로 변경했는데, 이런식으로 모듈화해서 사용하지 않고 그냥 views안에 중복되는 코드를 풀어쓰는것이 더 나을것 같다고 말씀하시는 건가요?? 연산에 대해 잘 알지 못하여 어느 방법이 더 좋은지 모르겠습니다 ㅠ

rating을 통한 정렬기능의 경우는 "평균 평점" 을 통해 정렬해야 했기에, 각 음료를 참조하는 review에서, 평균 rating을 계산하여 딕셔너리 형식으로 저장한 이후, 이 딕셔너리의 키값을 평균 평점에 따라 리스트에 정렬해주고, 이 정렬된 리스트를 기준으로 return 해줄 새로운 whole_data_list를 만들었습니다.
order_by를 사용하기 위해 order_by('-review__rating)' 을 이용하려 했는데, 연결된 review의 rating값들을 다 더해서 평균을 내줘야 하기에, field lookup을 통해서 rating의 평균을 구하는 방법을 잘 모르겠습니다..ㅠ

우선 rating에 따른 정렬 후 리스트를 생성하는 과정에서 리스트 컴프리헨션을 사용하는 방식으로 코드를 수정했습니다.

2022-03-08 01:48 UTC, kyeongraekim requested changes
영서님 이제 정말 거의 다 오셨네요! 아래 마지막 고민 사항 한 번만 생각해보시고 수정 혹은 의견 주세요!

2022-03-08 01:48 UTC, kyeongraekim commented on drinks/views.py
> +        filtered_drinks_with_annotation = filtered_drinks.annotate(average_rating = Avg('review__rating'), review_count=Count('review'))
13 번째 라인에 drink 전체 객체를 따로 안 잡고 35번 라인에서 한 번에 다 처리해주면 더 깔끔해질 것 같네요!
그리고 with_annotation이라는 부연설명이 다소 verbose하게 느껴집니다~ 깔끔하게 아래와 같이 줄여보는 건 어떨까요?


```python
drinks = Drink.objects.filter(q).annotate(average_rating = Avg('review__rating'), review_count=Count('review'))

2022-03-08 02:51 UTC, YEONG-CTRL commented on drinks/views.py
> +        filtered_drinks_with_annotation = filtered_drinks.annotate(average_rating = Avg('review__rating'), review_count=Count('review'))
수정했습니다~ 여러번 변수 선언할 필요 없이 한 줄로 처리하는 것이 더 깔끔한 방법인것 같아요!

2022-03-08 04:47 UTC, kyeongraekim approved these changes
LGTM!~

2022-03-08 05:03 UTC, merged