Feature/review
wecode-bootcamp-korea/30-1st-chadamhwa-backend pull request #5
Opened 2022-03-07 01:04 UTC by L-jungchan

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 로그인 된 유저만 리뷰를 남길수 있고 (리뷰는 한사람당 1개만 남길수 있음)
- 해당 드링크id에 포스팅 되어있는 리뷰를 get해서 화면에 보여주는 기능 구현

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. 리뷰 포스팅시 데이터 처리 
-먼저 로그인 된 사용자인지 로그인 데코레이터를 통해 토큰여부를 확인후 리뷰를 작성할수 있게끔 로직을 구현하였습니다.

2.리뷰 get
- 유저가 해당 드링크를 클릭해서 상세페이지로 넘어갔을때 해당 드링크에 포스팅되어있는 리뷰 데이터를 front로 넘겨주게 로직을 구현하였습니다.

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)

<br />

## :: 기타 질문 및 특이 사항

2022-03-07 02:05 UTC, kyeongraekim requested changes
아래 내용 확인하여서 수정해주세요!~

2022-03-07 02:05 UTC, kyeongraekim commented on reviews/urls.py
> +    path('/comment', CommentView.as_view())
restful하게 comments 복수형태로 진행해주세요!~ 그리고 review는 특정 product와 항상 물려 있을 것 으로 보이는데 Path 파라미터를 사용하는 것은 어떨까요?

2022-03-07 02:05 UTC, kyeongraekim commented on reviews/views.py
> +            drink = Drink.objects.get(name=data['drink']).id
drink 이름명을 받지 않고 위에서 언급한 것처럼 path 파라미터를 적용하면 불필요한 매핑은 필요 없어지겠네요!
프론트엔드와 함께 기획에 관해서 논의해주세요~

2022-03-07 02:05 UTC, kyeongraekim commented on reviews/views.py
> +                return JsonResponse({'message':'리뷰는 한번만 쓸수 있습니다!'}, status=400)
리뷰는 한 번만 쓸 수 있겠지만 언제든 해당 리뷰를 업데이트할 수 있게끔 기획해보면 어떨까요? 
update_or_create() 메소드를 한 번 검색하여서 사용해보세요!~
[장고 공식문서 쿼리셋 링크 바로가기](https://docs.djangoproject.com/en/4.0/ref/models/querysets/)

2022-03-07 02:05 UTC, kyeongraekim commented on reviews/views.py
> +            return JsonResponse({'review':result}, status=200)
해당 부분 보다 높은 가독성과 연산 효율을 위해 리스트 컴프리헨션을 적용하여 진행해보세요~

2022-03-07 02:05 UTC, kyeongraekim commented on reviews/views.py
> +                            'created_at' : str(review.created_at).split()[0]
해당 부분에 split 내용은 어떠한 기획과 의도에서 나왔는지 아래 코멘트로 설명 부탁드립니다!

2022-03-07 04:29 UTC, L-jungchan commented on reviews/views.py
> +                            'created_at' : str(review.created_at).split()[0]
<img width="376" alt="스크린샷 2022-03-07 오후 1 17 20" src="https://user-images.githubusercontent.com/91253866/156967725-85ea12ed-d834-4dc8-ad84-66bcb5de1a39.png">

시간까지 나오는게 좀 지저분해보여서 일단 지워봤습니다 
근데 지워놓고 보니 혹시 시간까지 나오는게 더 좋지 않을까? 라는 생각도 해봤지만 
실제로 술담화 페이지 리뷰도 년,월,일 까지만 나오길래 
그대로 구현해봤습니다!!

2022-03-07 08:53 UTC, L-jungchan commented on reviews/views.py
> +            drink = Drink.objects.get(name=data['drink']).id
path 파라미터 적용 완료했습니다

2022-03-08 16:12 UTC, kyeongraekim requested changes

2022-03-08 16:12 UTC, kyeongraekim commented on reviews/views.py
> +            """
해당 문자열 형태의 부연설명은 보통  def 함수 선언 직후에 이루어집니다. 다만 해당 내용은 코드 상에서의 부연설명이 더 필요할 때의 경우에 해당되며 위와 같은 내용은 코드 상에서 충분히  이해가 가는 내용으로 생각되어서 문자열 부연설명은 삭제해주심이 더 좋아 보이네요!

2022-03-08 16:12 UTC, kyeongraekim commented on reviews/views.py
> +
get() 메소드를 통해서 원하는 객체가 잡히지 않을 떄의 에러를 핸들링 해 주실 필요가 있어 보입니다!~

2022-03-09 06:24 UTC, kyeongraekim requested changes

2022-03-09 06:24 UTC, kyeongraekim commented on reviews/views.py
> +            return JsonResponse({'message':'review_posting_success'}, status=200)
create에 해당하는 보다 적절한 status code를 사용해주세요!~

2022-03-09 06:24 UTC, kyeongraekim commented on reviews/views.py
> +            Review.objects.update_or_create(
해당 부분을 객체를 잡아서 넣어주셔도 될 것 같아 보이네요. id의 정수값를 넣는 것이 아닌 아닌 객체로 update_or_create를 진행해주시면 데이터 무결성을 더 보존할 수 있는 기획이 될 것 같습니다~

2022-03-09 06:24 UTC, kyeongraekim commented on reviews/views.py
> +                'user' : User.objects.get(id=review.user_id).username,
get 함수에서 걸러주시는 (id=review.user_id) 에 해당하는 review.user_id는 어디서 값을 가져 온 후 넣어주는 것인지 궁금하네요!

2022-03-09 06:27 UTC, kyeongraekim requested changes

2022-03-09 06:27 UTC, kyeongraekim commented on reviews/views.py
> +                'created_at' : str(review.created_at).split()[0]
혹시 위 내용이 date내용만을 추출해서 전달하고자 인덱싱을 해주시는 것일까요? 그렇다면 장고선에서 date 값만을 추출하는 메소드를 찾아보고 적용해보세요!

2022-03-09 14:51 UTC, kyeongraekim requested changes

2022-03-09 14:51 UTC, kyeongraekim commented on reviews/views.py
> +        reviews = Review.objects.all()
drink_id에 물려있는 리뷰 객체들만을 잡으려고 하고 아래 리스트컴프리헨션 3항 연산자로로 적용 시켜 주신 것으로 보여집니다. 이곳에서 drink_id를 그냥 filter 로 걸어서 해당 객체의 쿼리셋만 잡아준다면 더 깔끔해질 것 으로 보입니다!~

2022-03-09 14:52 UTC, kyeongraekim requested changes

2022-03-09 14:52 UTC, kyeongraekim commented on reviews/views.py
> +                for review in reviews if review.drink.id == drink_id
이곳의 의미는 when의 의미적으로 접근하는게 if의 의미로 접근하는 것보다 옳아 보이네요! 앞선 리뷰에 대한 연장선 내용입니다! 참고해주세요

2022-03-10 08:38 UTC, kyeongraekim approved these changes
LGTM!~

2022-03-10 08:38 UTC, merged