[30기 안성준] 장바구니 기능 추가
wecode-bootcamp-korea/30-1st-chadamhwa-backend pull request #6
Opened 2022-03-07 07:37 UTC by sjoon21

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 사용자 장바구니 추가/조회/삭제/수량변경

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. 장바구니 추가
- 사용자가 제품과 수량을 선택을 하면 장바구니에 들어갑니다

2. 장바구니 조회
- 사용자가 장바구니 내에 있는 데이터를 조회 가능합니다. cart_id, drink_name, quantity, 그리고 price 항목이 조회를 할 수 있습니다.

3. 장바구니 삭제
- 사용자가 장바구니를 삭제 가능합니다

4. 장바구니 수량변경
-사용자가 장바구니 내에 제품 수량 조절이 가능합니다. 

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- 사용자가 장바구니를 제품을 넣기까지에 필요한 과정을 알게 되었습니다.
- 장바구니가 여러 테이블을 참조를 하기 때문에 로그인 데코레이터 뿐만 아니라 여러 data를 가져오는것을 배웠습니다
- 일반 for문이 아니라 Django에서 List Comprehension 를 써서 좀 더 효율적인 데이터 불러오는 방법을 배웠습니다
- request.GET.get() 같은 query string를 활요하는 방법을 배웠습니다.

<br />

## :: 기타 질문 및 특이 사항
-

2022-03-07 09:42 UTC, kyeongraekim requested changes

2022-03-07 09:42 UTC, kyeongraekim commented on orders/views.py
> +        return JsonResponse({'result' : result}, status = 201)
get 요청에 걸맞는 http 상태코드로 보여지지 않네요~

2022-03-07 09:42 UTC, kyeongraekim commented on orders/views.py
> +            drink_id = data['drink_id']
drink_id는 path parameter 형태로 받아보는 기획은 어떨까요?

2022-03-07 09:42 UTC, kyeongraekim commented on orders/views.py
> +            cart.quantity = quantity['data']
- data라는 키 값이 위 내용과 동일하여서 혼선을 줄 수 있곘네요! 해당 내용을 더 올바른 키 네이밍을 통해서 수정해주세요!
- 프론트에게 'id' 라는 값만 받는 내용이 다소 모호하게 보일 수 있겠네요!

2022-03-07 09:42 UTC, kyeongraekim commented on orders/views.py
> +            return JsonResponse({'message' : 'CART_DELETED'}, status = 201)
http status code를 다시 한 번 살펴봐주세요!

2022-03-08 06:14 UTC, kyeongraekim requested changes
아래의 내용도 추가 수정해주세요!~

2022-03-08 06:14 UTC, kyeongraekim commented on chadamhwa/urls.py
> +    path('damhwamarket', include('drinks.urls'))
restful 하게 작성해주시려면 damhwamarket 보다는 해당 리소스의 성질을 담는 drinks 등의 uri로 변경하는게 나아 보이네요~

2022-03-08 06:14 UTC, kyeongraekim commented on orders/views.py
> +
라인 한 줄이 불필요하게 띄어져있는데 공백 삭제해주세요~

2022-03-08 06:14 UTC, kyeongraekim commented on orders/views.py
> +            cart          = Cart.objects.get(id = data['cart_id'])
이곳에서의 get() 메소드도 DoesNotExist 에러 핸들링이 필요해 보일것 같네요!

2022-03-08 06:14 UTC, kyeongraekim commented on orders/views.py
> +            cart = request.GET.get('id')
delete도 패쓰 파라미터로 접근해서 사용해주세요~

2022-03-08 07:34 UTC, kyeongraekim requested changes

2022-03-08 07:34 UTC, kyeongraekim commented on orders/urls.py
> +    path('/cart/<int:drink_id>/<int:cart_id>', CartView.as_view())
path의 숫자 앞에 어떤 리소스의 아이디 값들이 들어 오는 것인지 에 대한 힌트가 될 수 있게 리소스 명을 id 값들 앞에 적어주세요~

2022-03-08 09:23 UTC, kyeongraekim requested changes

2022-03-08 09:23 UTC, kyeongraekim commented on orders/urls.py
> +    path('/cart/drink-id=<int:drink_id>/cart-id=<int:cart_id>', CartView.as_view())
계층간 구분은 슬래쉬로 해결해주시면 됩니다. 제가 추천드리는 URI는 아래와 같은데 한 번 참고해주세요~

```python
    path('/cart/<int:cart_id>/drink/<int:drink_id>', CartView.as_view())

2022-03-08 09:29 UTC, sjoon21 commented on orders/urls.py
> +    path('/cart/drink-id=<int:drink_id>/cart-id=<int:cart_id>', CartView.as_view())
수정했습니다! Query parameter부분이랑 헷갈린거 같습니다. : )

2022-03-08 09:44 UTC, kyeongraekim approved these changes
LGTM!~

2022-03-08 09:44 UTC, merged