mainview completed
wecode-bootcamp-korea/30-1st-chadamhwa-backend pull request #9
Opened 2022-03-08 12:43 UTC by YEONG-CTRL

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 메인페이지에서 농장별로 품목을 보여주기 위하여 최상위 딕셔너리에 키값으로 농장을 잡고, 그 안에 리스트를 만든 후, 리스트 안에 각 품목의 상세정보를 딕셔너리로 기입했습니다 ( 평점 평균이 높은 4개 품목만 리턴합니다)

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. 딕셔너리 - 리스트 - 딕셔너리의 형태를 만들기 위해 딕셔너리 컴프리헨션을 구현하고, 그 안에 리스트 컴프리헨션을 만들었습니다
2. 리뷰에 따른 정렬 및, 리뷰 평균값과 리뷰 개수값을 리턴하기위해 annotate와 order_by를 사용했습니다

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- 딕셔너리 - 리스트 컴프리헨션이 겹쳐져 있고, 역참조 -> annotate -> order_by -> 슬라이싱으로 이루어진 문법이 다소 가독성이 떨어져 보이는 것이 아닌가 생각되어 해당 부분을 고민했으나, 이중 for문을 돌리는 것보다 간결한 코드라 생각했습니다
<br />

## :: 기타 질문 및 특이 사항
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시)

2022-03-08 16:07 UTC, kyeongraekim requested changes

2022-03-08 16:07 UTC, kyeongraekim commented on drinks/views.py
> +class MainView(View):
데이터적인 관점에서 접근해야함을 다시 한 번 상기시켜드립니다. 어떠한 리소스에 대한 view인지를 더 명확하게 표현해주세요!

2022-03-08 16:07 UTC, kyeongraekim commented on drinks/views.py
> +        }for drink in farm.drink_set.all().annotate(average_rating = Avg('review__rating'), review_count=Count('review')).order_by('-average_rating')[:2]] for farm in farms}
[:2] 인덱싱 부분에 대한 부연 설명 아래 코멘트 형식으로 부탁드립니다~

2022-03-08 16:07 UTC, kyeongraekim commented on drinks/views.py
> +        }for drink in farm.drink_set.all().annotate(average_rating = Avg('review__rating'), review_count=Count('review')).order_by('-average_rating')[:2]] for farm in farms}
[:2] 인덱싱 부분에 대한 부연 설명 아래 코멘트 형식으로 부탁드립니다~

2022-03-09 00:51 UTC, YEONG-CTRL commented on drinks/views.py
> +class MainView(View):
main 페이지에 대한 view이니까 MainView로 해야지~ 하고 안일하게 생각했네요. 농장별 제품을 정렬해서 보여주는 view이기 때문에 FarmProductsView로 수정했습니다!

2022-03-09 00:52 UTC, YEONG-CTRL commented on drinks/views.py
> +        }for drink in farm.drink_set.all().annotate(average_rating = Avg('review__rating'), review_count=Count('review')).order_by('-average_rating')[:2]] for farm in farms}
술담화 메인 페이지와 마찬가지로, 어떠한 농장(테마)에 대한 상품을 몇개만 선정해서 보여주는 기능을 의도했기에 슬라이싱을 활용했습니다.

2022-03-09 06:30 UTC, kyeongraekim requested changes

2022-03-09 06:30 UTC, kyeongraekim commented on drinks/views.py
> +class MainView(View):
데이터적인 관점에서 접근해야함을 다시 한 번 상기시켜드립니다. 어떠한 리소스에 대한 view인지를 더 명확하게 표현해주세요!

2022-03-09 06:30 UTC, kyeongraekim commented on drinks/views.py
> +            "image"          : drink.drinkimage_set.all()[0].thumb_img
역참조 후 첫 번째 이미지를 추출하고 싶으신거면 .first() 메소드로 진행해주세요! 해당 메소드를 사용하는 이점도 추가로 한 번 학습해보세요~

2022-03-09 06:30 UTC, kyeongraekim commented on drinks/views.py
> +        }for drink in farm.drink_set.all().annotate(average_rating = Avg('review__rating'), review_count=Count('review')).order_by('-average_rating')[:4]] for farm in farms}
뒤에 인덱싱이 하드 코딩 되어 있는 것으로 보여지네요 혹시 어떠한 의도 일까요? 변수로 따로 빼서 보다 유용하게 관리할 수 있게 해주세요!~

2022-03-09 06:31 UTC, kyeongraekim requested changes

2022-03-09 06:31 UTC, kyeongraekim commented on drinks/views.py
> +class FarmProductsView(View):
클래스 명은 네이밍 컨벤션에 맞게 단수로 적어주셔야 합니다.

2022-03-09 07:03 UTC, YEONG-CTRL commented on drinks/views.py
> +            "image"          : drink.drinkimage_set.all()[0].thumb_img
수정했습니다! .get()과 마찬가지로 값이 없을때 None 을 반환하기에 예외처리가 용이한 점이 이점인듯 합니다.

2022-03-09 08:46 UTC, kyeongraekim requested changes

2022-03-09 08:46 UTC, kyeongraekim commented on drinks/views.py
> +        }for drink in farm.drink_set.all().annotate(average_rating = Avg('review__rating'), review_count=Count('review')).order_by('-average_rating')[:slicing_num]] for farm in farms}
제품에 대한 슬라이싱 기능은 이미 많이 들어보신 페이지네이션의 관점으로 접근하시면 됩니다. 프론트에게 오프셋 리밋 값을 전달 받아서 슬라이싱해주세요!

2022-03-09 09:17 UTC, YEONG-CTRL commented on drinks/views.py
> +        }for drink in farm.drink_set.all().annotate(average_rating = Avg('review__rating'), review_count=Count('review')).order_by('-average_rating')[:slicing_num]] for farm in farms}
수정했습니다~!

2022-03-09 09:19 UTC, kyeongraekim requested changes

2022-03-09 09:19 UTC, kyeongraekim commented on drinks/views.py
> +        limit = request.GET.get("limit", None)
offset, limit 값의 디폴트 값이 정해져있다면 프론트가 해당 내용을 쿼리스트링으로 못 전달 해도 기본 기획에서의 수량만큼은 데이터를 전달 할 수 있겠네요! 아까 4개로 슬라이싱하셨었는데  그와 동일한 결과를 내게 오프셋 리밋의 디폴트를 정해보세요~

2022-03-09 09:28 UTC, YEONG-CTRL commented on drinks/views.py
> +        limit = request.GET.get("limit", None)
안그래도 프론트 슬라이드를 구현할 수 있을지 애매해서 구현이 안되면 어떻게 할까 고민했는데 디폴트 값을 주면 해결되는 일이네요! 추가적으로 프론트 요청으로 drink의 id도 리턴해주는 딕셔너리 안에 넣을 수 있게 변경했습니다

2022-03-09 15:07 UTC, kyeongraekim requested changes

2022-03-09 15:07 UTC, kyeongraekim commented on drinks/views.py
> +        }for drink in farm.drink_set.all().annotate(average_rating = Avg('review__rating'), review_count=Count('review')).order_by('-average_rating')[offset:offset+limit]] for farm in farms}
다음의 형태를 띌 수 있게 코드 구조를 변경해주세요! 프론트에게 전달 할 때 farm에 대한 데이터 정보에 drinks가 nested 된 형태로 보내주는 것이 보다 올바른 형태이며, 각 farm에 대한 id 값, 이름 값도 따로 전달해주셔야 함을 유념해주세요. 프론트 측에게 해당 키값의 구조 변경이 가능할지 여부도 한 번 파악해주세요!

```python
        result = {
            "farms" : [{
                "id"   : farm.id
                "name" : farm.name
                "drinks" : {
                    "id"             : drink.id,
                    "name"           : drink.name,
                    "price"          : drink.price,
                    "average_rating" : drink.average_rating,
                    "review_count"   : drink.review_count,
                    "image"          : drink.drinkimage_set.all().first().thumb_img
                }
            ]}

2022-03-10 01:01 UTC, YEONG-CTRL commented on drinks/views.py
> +        }for drink in farm.drink_set.all().annotate(average_rating = Avg('review__rating'), review_count=Count('review')).order_by('-average_rating')[offset:offset+limit]] for farm in farms}
수정했습니다. farms는 farm의 이름 또는 아이디 값을 의미하신게 맞죠? 키값은 프론트랑 협의할 수 있는 사안인듯하여 수정했습니다

2022-03-10 01:46 UTC, kyeongraekim requested changes
.

2022-03-10 01:50 UTC, kyeongraekim requested changes

2022-03-10 01:50 UTC, kyeongraekim commented on drinks/views.py
> +            }for drink in farm.drink_set.all().annotate(average_rating = Avg('review__rating'), review_count=Count('review')).order_by('-average_rating')[offset:offset+limit]] for farm in farms}
61번 째 라인에 farm.name이 바로 들어가게 되면 각각의 데이터 농장 내역들이 들어 갈 것으로 보여집니다. 즉 value에 들어갈법한 내용이 key 값으로 들어감을 의미합니다. 제가 요청드린 내용 다시 한 번 살펴보시면서,
예를들어 농장의 이름만을 추출하고 싶을 때 프론트 측이 result[farm][name] 의 형태로 중첩된 딕셔너리의 매핑이 가능하게끔 수정해주세요!

2022-03-10 02:42 UTC, YEONG-CTRL commented on drinks/views.py
> +            }for drink in farm.drink_set.all().annotate(average_rating = Avg('review__rating'), review_count=Count('review')).order_by('-average_rating')[offset:offset+limit]] for farm in farms}
result[farm][name] 에서 중간의  [farm]은 무슨 키값을 말씀하시는걸까요? result라는 딕셔너리 안에 farm이라는 큰 키를 만들고 그 키의 값에 농장의 name, 농장의 id, 농장에 해당하는 drinks를 키로 둔 이후 각각 값을 넣어주란 말씀일까요? 
<img width="768" alt="image" src="https://user-images.githubusercontent.com/79896709/157577443-e54b818f-d88e-4420-ae9d-4d75ef28cf92.png">

이러한 결과가 나오게 코드를 수정하긴 했는데 정확히 farms 키값이 무엇을 의미하는지 모르겠습니다

2022-03-10 02:42 UTC, YEONG-CTRL commented on drinks/views.py
> +            }for drink in farm.drink_set.all().annotate(average_rating = Avg('review__rating'), review_count=Count('review')).order_by('-average_rating')[offset:offset+limit]] for farm in farms}
주신 코드처럼 farms를 키값으로 설정하면 TypeError가 나게 됩니다

2022-03-10 02:42 UTC, YEONG-CTRL commented on drinks/views.py
> +            }for drink in farm.drink_set.all().annotate(average_rating = Avg('review__rating'), review_count=Count('review')).order_by('-average_rating')[offset:offset+limit]] for farm in farms}
일단 수정해서 다시 push했습니다

2022-03-10 06:32 UTC, kyeongraekim requested changes

2022-03-10 06:32 UTC, kyeongraekim commented on drinks/views.py
> +                    "name"  : farm.name,
이곳 정렬 한 번만 봐주세요! 그러면 바로 머지 해드리겠습니다~

2022-03-10 06:37 UTC, kyeongraekim approved these changes
LGTM!~

2022-03-10 06:37 UTC, merged